version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ${DATABASE_PATH}:/database
      - ${DATABASE_CONFIG}:/run/secrets
    ports:
      - 5432:5432
    environment:
      TZ: UTC-8
      PGDATA: /database
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password